/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://lzrzw7vawnghpot54quhpqmfuu.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fmsjsngy4fcwhm3wbar3ndda74",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://co969qj4nh.execute-api.eu-west-2.amazonaws.com/staging",
            "region": "eu-west-2"
        }
    ],
    "aws_cognito_identity_pool_id": "eu-west-2:c7983476-877c-4f9f-91a6-86bb2dd9b24a",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_oZqahSKLD",
    "aws_user_pools_web_client_id": "6ran2r3n25cat59m98c6tlujrn",
    "oauth": {}
};


export default awsmobile;
